"""Add UserLike table and Article likes_count

Revision ID: 0fe51ee41b0b
Revises: a1b2c3d4e5f6
Create Date: 2026-08-02 13:51:38.535960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe51ee41b0b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_likes_article_id'), 'user_likes', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_likes_user_id'), 'user_likes', ['user_id'], unique=False)
    op.add_column('articles', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.alter_column('articles', 'sentiment',
               existing_type=postgresql.ENUM('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', name='sentimentlabel'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_articles_likes_count'), 'articles', ['likes_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_likes_count'), table_name='articles')
    op.alter_column('articles', 'sentiment',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', name='sentimentlabel'),
               existing_nullable=True)
    op.drop_column('articles', 'likes_count')
    op.drop_index(op.f('ix_user_likes_user_id'), table_name='user_likes')
    op.drop_index(op.f('ix_user_likes_article_id'), table_name='user_likes')
    op.drop_table('user_likes')
    # ### end Alembic commands ###
