"""init

Revision ID: 94a5041843e2
Revises: 
Create Date: 2026-08-01 08:32:26.496165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94a5041843e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=550), nullable=True),
    sa.Column('type', sa.Enum('PERSON', 'COMPANY', 'COUNTRY', 'ORGANIZATION', 'PRODUCT', 'TECHNOLOGY', 'CURRENCY', 'EVENT_TYPE', 'OTHER', name='entitytype'), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('wikidata_id', sa.String(length=50), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_entities_country'), 'entities', ['country'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_slug'), 'entities', ['slug'], unique=True)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('slug', sa.String(length=1100), nullable=True),
    sa.Column('summary_short', sa.Text(), nullable=True),
    sa.Column('summary_medium', sa.Text(), nullable=True),
    sa.Column('summary_bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', name='eventsentiment'), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('trending', sa.Boolean(), nullable=True),
    sa.Column('breaking', sa.Boolean(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_breaking'), 'events', ['breaking'], unique=False)
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_country'), 'events', ['country'], unique=False)
    op.create_index(op.f('ix_events_first_seen'), 'events', ['first_seen'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_trending'), 'events', ['trending'], unique=False)
    op.create_index(op.f('ix_events_verified'), 'events', ['verified'], unique=False)
    op.create_table('publishers',
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('rss_feeds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.create_index(op.f('ix_publishers_active'), 'publishers', ['active'], unique=False)
    op.create_index(op.f('ix_publishers_country'), 'publishers', ['country'], unique=False)
    op.create_index(op.f('ix_publishers_slug'), 'publishers', ['slug'], unique=True)
    op.create_table('system_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_service'), 'system_logs', ['service'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('READER', 'JOURNALIST', 'RESEARCHER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_provider_id'), 'users', ['oauth_provider_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('articles',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('slug', sa.String(length=1100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', name='sentimentlabel'), nullable=True),
    sa.Column('published_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('RAW', 'PARSED', 'PROCESSED', 'PUBLISHED', 'FAILED', name='articlestatus'), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('reading_time_min', sa.Integer(), nullable=True),
    sa.Column('is_paywalled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_collected_time'), 'articles', ['collected_time'], unique=False)
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    op.create_index(op.f('ix_articles_country'), 'articles', ['country'], unique=False)
    op.create_index(op.f('ix_articles_language'), 'articles', ['language'], unique=False)
    op.create_index(op.f('ix_articles_published_time'), 'articles', ['published_time'], unique=False)
    op.create_index(op.f('ix_articles_publisher_id'), 'articles', ['publisher_id'], unique=False)
    op.create_index(op.f('ix_articles_sentiment'), 'articles', ['sentiment'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_index(op.f('ix_articles_url_hash'), 'articles', ['url_hash'], unique=True)
    op.create_table('collection_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('publisher_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('articles_found', sa.String(length=20), nullable=True),
    sa.Column('articles_new', sa.String(length=20), nullable=True),
    sa.Column('articles_duplicate', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_collection_runs_publisher_id'), 'collection_runs', ['publisher_id'], unique=False)
    op.create_table('ai_summaries',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('summary_short', sa.Text(), nullable=True),
    sa.Column('summary_medium', sa.Text(), nullable=True),
    sa.Column('summary_bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('reading_time_min', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_ai_summaries_article_id'), 'ai_summaries', ['article_id'], unique=True)
    op.create_table('article_embeddings',
    sa.Column('embedding_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.PrimaryKeyConstraint('embedding_id')
    )
    op.create_index(op.f('ix_article_embeddings_article_id'), 'article_embeddings', ['article_id'], unique=True)
    op.create_table('article_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_entities_article_id'), 'article_entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_entities_entity_id'), 'article_entities', ['entity_id'], unique=False)
    op.create_table('event_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_articles_article_id'), 'event_articles', ['article_id'], unique=False)
    op.create_index(op.f('ix_event_articles_event_id'), 'event_articles', ['event_id'], unique=False)
    op.create_table('trust_signals',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('official_source', sa.Boolean(), nullable=True),
    sa.Column('independent_sources', sa.Integer(), nullable=True),
    sa.Column('publisher_reputation', sa.Float(), nullable=True),
    sa.Column('cross_confirmation', sa.Boolean(), nullable=True),
    sa.Column('has_correction', sa.Boolean(), nullable=True),
    sa.Column('freshness_hours', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('signal_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_trust_signals_article_id'), 'trust_signals', ['article_id'], unique=True)
    op.create_index(op.f('ix_trust_signals_confidence_score'), 'trust_signals', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_trust_signals_event_id'), 'trust_signals', ['event_id'], unique=False)
    op.create_table('user_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bookmarks_article_id'), 'user_bookmarks', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_bookmarks_event_id'), 'user_bookmarks', ['event_id'], unique=False)
    op.create_index(op.f('ix_user_bookmarks_user_id'), 'user_bookmarks', ['user_id'], unique=False)
    op.create_table('user_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_pct', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_history_article_id'), 'user_history', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_history_user_id'), 'user_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_history_user_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_article_id'), table_name='user_history')
    op.drop_table('user_history')
    op.drop_index(op.f('ix_user_bookmarks_user_id'), table_name='user_bookmarks')
    op.drop_index(op.f('ix_user_bookmarks_event_id'), table_name='user_bookmarks')
    op.drop_index(op.f('ix_user_bookmarks_article_id'), table_name='user_bookmarks')
    op.drop_table('user_bookmarks')
    op.drop_index(op.f('ix_trust_signals_event_id'), table_name='trust_signals')
    op.drop_index(op.f('ix_trust_signals_confidence_score'), table_name='trust_signals')
    op.drop_index(op.f('ix_trust_signals_article_id'), table_name='trust_signals')
    op.drop_table('trust_signals')
    op.drop_index(op.f('ix_event_articles_event_id'), table_name='event_articles')
    op.drop_index(op.f('ix_event_articles_article_id'), table_name='event_articles')
    op.drop_table('event_articles')
    op.drop_index(op.f('ix_article_entities_entity_id'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_article_id'), table_name='article_entities')
    op.drop_table('article_entities')
    op.drop_index(op.f('ix_article_embeddings_article_id'), table_name='article_embeddings')
    op.drop_table('article_embeddings')
    op.drop_index(op.f('ix_ai_summaries_article_id'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    op.drop_index(op.f('ix_collection_runs_publisher_id'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_articles_url_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_sentiment'), table_name='articles')
    op.drop_index(op.f('ix_articles_publisher_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_published_time'), table_name='articles')
    op.drop_index(op.f('ix_articles_language'), table_name='articles')
    op.drop_index(op.f('ix_articles_country'), table_name='articles')
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_collected_time'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_logs_service'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_publishers_slug'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_country'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_active'), table_name='publishers')
    op.drop_table('publishers')
    op.drop_index(op.f('ix_events_verified'), table_name='events')
    op.drop_index(op.f('ix_events_trending'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_first_seen'), table_name='events')
    op.drop_index(op.f('ix_events_country'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_index(op.f('ix_events_breaking'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_slug'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_country'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
